using System.Text.Json;
using Agterhuis.Ui.Designer.Model;
using Agterhuis.Ui.Designer.Registry;
using Agterhuis.Ui.Designer.Serialization;
using Microsoft.AspNetCore.Components.Web;

namespace Agterhuis.Ui.Designer.CodeGen;

/// <summary>
/// Generates clean, deterministic Razor code from a DesignPage model.
/// Ensures:
/// - Correct indentation and formatting (human-readable)
/// - Parameters in logical order (only non-default values)
/// - Token-only colors (no hardcoded hex)
/// - Proper Label/AriaLabel on form controls
/// - Deterministic: same input => byte-identical output
/// </summary>
public sealed class RazorCodeGenerator
{
    private const string GeneratorVersion = "1.0";
    private const string IndentUnit = "    ";
    private readonly RazorFormatter _formatter;
    private readonly DesignerComponentRegistry _registry;
    private readonly DateTime? _testTimestamp; // For testing determinism

    public RazorCodeGenerator(DesignerComponentRegistry? registry = null, DateTime? testTimestamp = null)
    {
        _registry = registry ?? DesignerComponentRegistry.Instance;
        _formatter = new RazorFormatter(4);
        _testTimestamp = testTimestamp;
    }

    /// <summary>
    /// Generates Razor code for a DesignPage.
    /// </summary>
    public string GeneratePageCode(DesignPage page, DesignDocument document)
    {
        ArgumentNullException.ThrowIfNull(page);
        ArgumentNullException.ThrowIfNull(document);

        var pageIndex = document.Pages.FindIndex(candidate => ReferenceEquals(candidate, page));
        var qualityErrors = pageIndex >= 0
            ? CodeGenerationGuard.ValidatePageForCodeGen(page, _registry, pageIndex)
            : CodeGenerationGuard.ValidatePageForCodeGen(page, _registry);
        if (qualityErrors.Count > 0)
        {
            throw new InvalidOperationException(string.Join("; ", qualityErrors.Select(error => $"{error.Path}: {error.Message}")));
        }

        var lines = new List<string>();

        // Header with generator version (timestamp omitted for determinism in production)
        lines.Add($"@* Generated by Agterhuis.Ui Designer v{GeneratorVersion}");
        lines.Add($"   Document: {document.Name}");
        if (_testTimestamp.HasValue)
        {
            lines.Add($"   Generated: {_testTimestamp:O} *@");
        }
        else
        {
            lines.Add("*@");
        }
        lines.Add("");

        // Page directive
        lines.Add($"@page \"{page.Route}\"");
        lines.Add($"@rendermode InteractiveWebAssembly");
        lines.Add("");

        // Page title (single line for cleaner output)
        lines.Add($"<PageTitle>{page.Title}</PageTitle>");
        lines.Add("");

        // Root structure
        lines.Add("<MainLayout>");

        // Generate the node tree (typically starting with rows/columns)
        foreach (var node in page.Nodes)
        {
            GenerateNodeCode(node, lines, indentLevel: 1);
        }

        lines.Add("</MainLayout>");

        var eventHandlers = CollectEventHandlers(page);

        // Code section
        lines.Add("");
        lines.Add("@code {");
        if (eventHandlers.Count == 0)
        {
            lines.Add("    // TODO: Add component logic here");
        }
        else
        {
            foreach (var method in eventHandlers)
            {
                foreach (var methodLine in method)
                {
                    lines.Add(methodLine);
                }

                lines.Add("");
            }

            lines.RemoveAt(lines.Count - 1);
        }

        lines.Add("}");

        var code = string.Join(Environment.NewLine, lines);
        return _formatter.Normalize(code);
    }

    /// <summary>
    /// Recursively generates code for a node and its children.
    /// </summary>
    private void GenerateNodeCode(DesignNode node, List<string> lines, int indentLevel)
    {
        if (!_registry.TryGetDescriptor(node.ComponentType, out var descriptor))
        {
            // Fallback for unknown components (skip)
            return;
        }

        var indent = string.Concat(Enumerable.Repeat(IndentUnit, indentLevel));
        var openingTag = new List<string> { node.ComponentType };
        lines.Add($"{indent}@* agt-node:{node.Id} *@");

        // Add parameters, sorted deterministically
        var parameterLines = GenerateParameterLines(node, descriptor);
        if (parameterLines.Count == 0)
        {
            // Self-closing or empty: <Component />
            lines.Add($"{indent}<{node.ComponentType} />");
        }
        else if (node.Children.Count == 0 && !HasSlotContent(descriptor))
        {
            // No children and no slots: <Component param="value" />
            var parameterText = string.Join(" ", parameterLines);
            lines.Add($"{indent}<{node.ComponentType} {parameterText} />");
        }
        else
        {
            // Opening tag with parameters
            if (parameterLines.Count <= 2)
            {
                // Fit on one line
                var parameterText = string.Join(" ", parameterLines);
                lines.Add($"{indent}<{node.ComponentType} {parameterText}>");
            }
            else
            {
                // Multi-line parameters
                lines.Add($"{indent}<{node.ComponentType}");
                foreach (var paramLine in parameterLines)
                {
                    lines.Add($"{indent}{IndentUnit}{paramLine}");
                }
                lines.Add($"{indent}>");
            }

            // Render children by slot
            foreach (var (slotName, children) in node.Children.OrderBy(x => x.Key, StringComparer.Ordinal))
            {
                if (descriptor.Slots.Contains(slotName))
                {
                    if (slotName != "ChildContent")
                    {
                        lines.Add($"{indent}{IndentUnit}<{slotName}>");
                    }

                    foreach (var child in children)
                    {
                        GenerateNodeCode(child, lines, indentLevel + (slotName != "ChildContent" ? 2 : 1));
                    }

                    if (slotName != "ChildContent")
                    {
                        lines.Add($"{indent}{IndentUnit}</{slotName}>");
                    }
                }
            }

            // Closing tag
            lines.Add($"{indent}</{node.ComponentType}>");
        }
    }

    /// <summary>
    /// Generates parameter attribute lines, sorted deterministically.
    /// Only outputs non-default parameters.
    /// </summary>
    private List<string> GenerateParameterLines(DesignNode node, DesignerComponentDescriptor descriptor)
    {
        var parameters = new List<string>();

        foreach (var paramDesc in descriptor.Parameters.OrderBy(p => p.Name, StringComparer.Ordinal))
        {
            if (!node.Parameters.TryGetValue(paramDesc.Name, out var paramValue))
            {
                continue;
            }

            if (paramValue.Literal is null && paramValue.Expression is null && string.IsNullOrWhiteSpace(paramValue.EventHandlerName))
            {
                continue;
            }

            if (paramDesc.IsEventCallback)
            {
                if (!string.IsNullOrWhiteSpace(paramValue.EventHandlerName))
                {
                    parameters.Add($"{paramDesc.Name}=\"{EscapeQuotes(paramValue.EventHandlerName)}\"");
                }

                continue;
            }

            var valueStr = FormatParameterValue(paramValue, paramDesc);
            if (string.IsNullOrEmpty(valueStr))
            {
                continue;
            }

            parameters.Add($"@{paramDesc.Name}=\"{EscapeQuotes(valueStr)}\"");
        }

        if (SupportsUnmatchedAttributes(descriptor))
        {
            if (node.InlineStyles.Count > 0)
            {
                var styleValue = string.Join("; ", node.InlineStyles
                    .OrderBy(static entry => entry.Key, StringComparer.OrdinalIgnoreCase)
                    .Select(static entry => $"{entry.Key}: {entry.Value}"));
                parameters.Add($"style=\"{EscapeQuotes(styleValue)}\"");
            }

            foreach (var (key, value) in node.CustomAttributes.OrderBy(static entry => entry.Key, StringComparer.OrdinalIgnoreCase))
            {
                if (string.IsNullOrWhiteSpace(key) || string.IsNullOrWhiteSpace(value))
                {
                    continue;
                }

                parameters.Add($"{key}=\"{EscapeQuotes(value)}\"");
            }
        }

        return parameters;
    }

    /// <summary>
    /// Formats a parameter value from the design model.
    /// </summary>
    private static string FormatParameterValue(DesignParameterValue paramValue, ComponentParameterDescriptor descriptor)
    {
        if (paramValue.Expression is not null)
        {
            // Expression (e.g., C# code) — pass through as-is
            return paramValue.Expression;
        }

        if (paramValue.Literal is null)
        {
            return string.Empty;
        }

        // Determine the type and format accordingly
        var literalStr = paramValue.Literal.ToString();

        // Handle booleans specially
        if (descriptor.ParameterType == typeof(bool))
        {
            return literalStr.Equals("true", StringComparison.OrdinalIgnoreCase) ? "true" : "false";
        }

        // Handle numbers
        if (descriptor.ParameterType.IsValueType && descriptor.ParameterType != typeof(string))
        {
            return literalStr;
        }

        // Default: return as string
        return literalStr;
    }

    /// <summary>
    /// Escapes quotes for HTML attributes.
    /// </summary>
    private static string EscapeQuotes(string value)
    {
        return value.Replace("\"", "&quot;", StringComparison.Ordinal);
    }

    /// <summary>
    /// Checks if a component descriptor has meaningful slot content.
    /// </summary>
    private static bool HasSlotContent(DesignerComponentDescriptor descriptor)
    {
        return descriptor.Slots.Count > 0;
    }

    private static bool SupportsUnmatchedAttributes(DesignerComponentDescriptor descriptor)
    {
        return descriptor.Parameters.Any(parameter => string.Equals(parameter.Name, "Attributes", StringComparison.Ordinal));
    }

    private IReadOnlyList<IReadOnlyList<string>> CollectEventHandlers(DesignPage page)
    {
        var handlers = new Dictionary<string, string>(StringComparer.Ordinal);
        CollectEventHandlersFromNodes(page.Nodes, handlers);

        var result = new List<IReadOnlyList<string>>(handlers.Count);
        foreach (var (handlerName, eventTypeName) in handlers.OrderBy(static item => item.Key, StringComparer.Ordinal))
        {
            if (string.Equals(eventTypeName, nameof(MouseEventArgs), StringComparison.Ordinal))
            {
                result.Add(
                [
                    $"    private void {handlerName}(MouseEventArgs args)",
                    "    {",
                    "        // TODO: implementeer logica",
                    "    }"
                ]);
            }
            else
            {
                result.Add(
                [
                    $"    private void {handlerName}()",
                    "    {",
                    "        // TODO: implementeer logica",
                    "    }"
                ]);
            }
        }

        return result;
    }

    private void CollectEventHandlersFromNodes(IEnumerable<DesignNode> nodes, Dictionary<string, string> handlers)
    {
        foreach (var node in nodes)
        {
            if (_registry.TryGetDescriptor(node.ComponentType, out var descriptor))
            {
                foreach (var parameter in descriptor.Parameters.Where(static candidate => candidate.IsEventCallback))
                {
                    if (!node.Parameters.TryGetValue(parameter.Name, out var value)
                        || string.IsNullOrWhiteSpace(value?.EventHandlerName))
                    {
                        continue;
                    }

                    handlers.TryAdd(
                        value.EventHandlerName,
                        ResolveEventArgTypeName(parameter.TypeName));
                }
            }

            foreach (var childSlot in node.Children.Values)
            {
                CollectEventHandlersFromNodes(childSlot, handlers);
            }
        }
    }

    private static string ResolveEventArgTypeName(string parameterTypeName)
    {
        const string marker = "EventCallback<";
        var markerIndex = parameterTypeName.IndexOf(marker, StringComparison.Ordinal);
        if (markerIndex < 0)
        {
            return "void";
        }

        var start = markerIndex + marker.Length;
        var end = parameterTypeName.IndexOf('>', start);
        if (end <= start)
        {
            return "void";
        }

        var genericArgument = parameterTypeName[start..end].Trim();
        return string.IsNullOrWhiteSpace(genericArgument) ? "void" : genericArgument;
    }
}
