using System.Text;
using Agterhuis.Ui.Designer.CodeGen;
using Agterhuis.Ui.Designer.Model;
using Agterhuis.Ui.Designer.Registry;

namespace Agterhuis.Ui.Designer.Tests.CodeGen;

public class RazorCodeGeneratorTests
{
    private readonly RazorCodeGenerator _generator;

    public RazorCodeGeneratorTests()
    {
        _generator = new RazorCodeGenerator();
    }

    [Fact]
    public void GeneratePageCode_WithSimplePage_ProducesValidRazor()
    {
        // Arrange
        var document = new DesignDocument
        {
            Name = "Test Document",
            Version = "1.0"
        };

        var page = new DesignPage
        {
            Route = "/test",
            Title = "Test Page",
            Nodes = []
        };

        // Act
        var code = _generator.GeneratePageCode(page, document);

        // Assert
        Assert.NotEmpty(code);
        Assert.Contains("@page \"/test\"", code);
        Assert.Contains("<PageTitle>Test Page</PageTitle>", code);
        Assert.Contains("<MainLayout>", code);
        Assert.Contains("</MainLayout>", code);
    }

    [Fact]
    public void GeneratePageCode_IsDeterministic()
    {
        // Arrange
        var testTimestamp = new DateTime(2024, 1, 1, 12, 0, 0, DateTimeKind.Utc);
        var codeGen1 = new RazorCodeGenerator(testTimestamp: testTimestamp);
        var codeGen2 = new RazorCodeGenerator(testTimestamp: testTimestamp);

        var document = new DesignDocument
        {
            Name = "Determinism Test",
            Version = "1.0"
        };

        var page = new DesignPage
        {
            Route = "/determinism",
            Title = "Determinism Test Page",
            Nodes =
            [
                new DesignNode
                {
                    Id = "node1",
                    ComponentType = "AgtTextField",
                    Parameters = new()
                    {
                        ["Label"] = new() { Literal = System.Text.Json.Nodes.JsonNode.Parse("\"Test Input\"") }
                    }
                }
            ]
        };

        // Act
        var code1 = codeGen1.GeneratePageCode(page, document);
        var code2 = codeGen2.GeneratePageCode(page, document);

        // Assert: same input should produce byte-identical output
        var bytes1 = Encoding.UTF8.GetBytes(code1);
        var bytes2 = Encoding.UTF8.GetBytes(code2);

        Assert.Equal(bytes1, bytes2);
    }

    [Fact]
    public void GeneratePageCode_IncludesGeneratorHeader()
    {
        // Arrange
        var document = new DesignDocument { Name = "Header Test" };
        var page = new DesignPage { Route = "/", Title = "Test" };

        // Act
        var code = _generator.GeneratePageCode(page, document);

        // Assert
        Assert.Contains("@* Generated by Agterhuis.Ui Designer v", code);
        Assert.Contains("Document: Header Test", code);
    }

    [Fact]
    public void GeneratePageCode_WithEmptyPage_StillProducesValidStructure()
    {
        // Arrange
        var document = new DesignDocument { Name = "Empty" };
        var page = new DesignPage { Route = "/empty", Title = "Empty Page" };

        // Act
        var code = _generator.GeneratePageCode(page, document);

        // Assert
        Assert.Contains("@page \"/empty\"", code);
        Assert.Contains("<PageTitle>Empty Page</PageTitle>", code);
        Assert.Contains("<MainLayout>", code);
        Assert.Contains("</MainLayout>", code);
    }

    [Fact]
    public void RazorFormatter_Indent_AddsCorrectSpaces()
    {
        // Arrange
        var formatter = new RazorFormatter(indentSize: 4);

        // Act
        var indented = formatter.Indent("test", 2);

        // Assert
        Assert.Equal("        test", indented); // 8 spaces (2 levels * 4 spaces)
    }

    [Fact]
    public void RazorFormatter_Normalize_RemovesTrailingWhitespace()
    {
        // Arrange
        var formatter = new RazorFormatter();
        var input = "line1   \r\nline2  \nline3";

        // Act
        var normalized = formatter.Normalize(input);

        // Assert
        var lines = normalized.Split(Environment.NewLine);
        Assert.All(lines, line => Assert.False(line.EndsWith(" "), $"Line '{line}' has trailing space"));
    }
}
